[project]
name = "VAULT"
version = "0.1.0"
description = "VAULT for file encryption and decryption"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "art>=6.5",
    "cryptography>=46.0.3",
    "pyinstaller>=6.18.0",
]
